universe		= docker
docker_image		= pytorch/pytorch:2.3.1-cuda12.1-cudnn8-devel
executable              = pytorch_matmul.py
output                  = runlogs/pytorch_matmul.$(ClusterId).$(ProcId).out
error                   = runlogs/pytorch_matmul.$(ClusterId).$(ProcId).err
log                     = runlogs/pytorch_matmul.$(ClusterId).log
should_transfer_files   = YES
request_GPUs = 1
request_CPUs = 1
request_memory = 1G
requirements = UidDomain == "cs.uni-saarland.de" 
+WantGPUHomeMounted = true
+WantScratchMounted = true
queue 1
