universe		= docker
docker_image            = nvcr.io/nvidia/tensorflow:25.02-tf2-py3
executable              = tf_matmul_docker.py
output                  = runlogs/tf_matmul.$(ClusterId).$(ProcId).out
error                   = runlogs/tf_matmul.$(ClusterId).$(ProcId).err
log                     = runlogs/tf_matmul.$(ClusterId).log
should_transfer_files   = YES
request_GPUs = 1
request_CPUs = 1
request_memory = 1G
requirements = UidDomain == "cs.uni-saarland.de" 
+WantGPUHomeMounted = true
+WantScratchMounted = true
queue 1
